# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20201117_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
    ]
